/**
 * StarCraft: Ghost (Xbox dev build) - Recompiled Game Entry Point
 *
 * This is the Windows executable that hosts the recompiled game code.
 * Initialization sequence:
 *
 * 1. Redirect stdio to a log file (Proton gives a console its own console)
 * 2. Load the original XBE file from disk
 * 3. Initialize the Xbox memory layout (map data sections to original VAs)
 * 4. Initialize the Xbox kernel replacement layer + input + USB/OHCI
 * 5. Initialize the kernel bridge (thunk table in Xbox memory)
 * 6. Install the NV2A software-method dispatcher (present/fence/vblank)
 * 7. Set up game file paths for I/O redirection, initialize the stack
 * 8. Install VEH crash handler for diagnostics
 * 9. Call the game's original entry point (recompiled)
 *
 * The NV2A setup mirrors the known-working scghost-recomp port
 * (refs/scghost-recomp/src/main.c): without push-buffer execution, native
 * fences, the software-method handler and vblank delivery the title waits on
 * hardware that never advances and the boot stalls after one clear.
 *
 * XBE Details:
 *   Title:       StarCraft: Ghost (Xbox dev build)
 *   Title ID:    0x00000002
 *   Base addr:   0x00010000
 *   Entry point: 0x001B3FBB (mainCRTStartup)
 */

#include <windows.h>
#include <dbghelp.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>

/* xboxrecomp runtime headers */
#include <xbox/xboxrecomp.h>
#include "ohci.h"
#include "xinput_xbox.h"
#include "apu.h"

/* ── Global register state (defined in xbox_memory_layout.c) ── */

/* RECOMP_TLS is not optional here. The runtime defines these thread-local, and
 * a plain `extern` referencing a __declspec(thread) variable does not resolve
 * to the calling thread's copy -- it resolves to the image's TLS template. */
extern RECOMP_TLS uint32_t g_eax, g_ecx, g_edx, g_esp;
extern RECOMP_TLS uint32_t g_ebx, g_esi, g_edi;
extern RECOMP_TLS uint32_t g_seh_ebp;
extern RECOMP_TLS uint32_t g_fs_base;
extern RECOMP_TLS double g_fp_stack[8];
extern RECOMP_TLS int g_fp_top;
extern RECOMP_TLS uint16_t g_fp_control_word;
extern RECOMP_TLS int g_fp_cmp;
extern RECOMP_TLS RecompXmm g_xmm0, g_xmm1, g_xmm2, g_xmm3;
extern RECOMP_TLS RecompXmm g_xmm4, g_xmm5, g_xmm6, g_xmm7;
extern ptrdiff_t g_xbox_mem_offset;

/* Declared in the generated recomp_types.h. main.c deliberately does not pull
 * that header in (it re-declares the register file above), so declare this here
 * too -- MSVC accepts the implicit declaration, clang does not. */
extern int recomp_dispatch_init(void);

/* ── XBE Constants ─────────────────────────────────────────── */

#define YOUR_GAME_TITLE         "StarCraft: Ghost"
#define YOUR_GAME_ENTRY_POINT   0x001B3FBB  /* XBE entry point VA */
#define YOUR_GAME_XBE_PATH      "game\\Ghost.xbe"
#define YOUR_GAME_DIR            "game"

/* ── Forward declarations ──────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size);

/* Recompiled entry point (generated by recomp pipeline):
 * mainCRTStartup at XBE entry VA 0x001B3FBB (from Ghost.map). */
extern void mainCRTStartup_001B3FBB(void);

/* ── VEH crash handler ─────────────────────────────────────── */

static void print_guest_context(void *rip)
{
    char buf[sizeof(SYMBOL_INFO) + 256];
    SYMBOL_INFO *sym = (SYMBOL_INFO *)buf;
    DWORD64 disp = 0;

    memset(buf, 0, sizeof(buf));
    sym->SizeOfStruct = sizeof(SYMBOL_INFO);
    sym->MaxNameLen = 255;
    if (SymFromAddr(GetCurrentProcess(), (DWORD64)(uintptr_t)rip, &disp, sym))
        fprintf(stderr, "  in %s+0x%llX\n",
                sym->Name, (unsigned long long)disp);

    if (g_xbox_mem_offset && g_esp) {
        const uint32_t *sp =
            (const uint32_t *)((uintptr_t)g_xbox_mem_offset + g_esp);
        int shown = 0, i;
        fprintf(stderr, "  guest stack (return addresses, innermost first):\n");
        for (i = 0; i < 256 && shown < 24; i++) {
            uint32_t v = sp[i];
            if (v > g_xbox_code_lo && v < g_xbox_code_hi) {
                fprintf(stderr, "    [esp+%-4d] 0x%08X\n", i * 4, v);
                shown++;
            }
        }
        if (!shown)
            fprintf(stderr, "    (no return addresses in range)\n");

        if (!shown) {
            uint32_t k;
            extern volatile uint32_t g_icall_trace[16];
            extern volatile uint32_t g_icall_trace_idx;

            fprintf(stderr, "  recent ICALL targets:");
            for (k = 0; k < 16; k++)
                fprintf(stderr, " %08X",
                        g_icall_trace[(g_icall_trace_idx + k) & 15]);
            fprintf(stderr, "\n");

            for (i = 0; i < 20; i++)
                fprintf(stderr, "    raw[esp+%-4d] 0x%08X\n", i * 4, sp[i]);
        }
    }
}

/* The emulated APU. */
extern MCPXAPUState *g_apu_state;
extern bool apu_hook_handle_mmio(PCONTEXT ctx, uintptr_t fault_addr,
                                 uint32_t fault_xbox_va, int is_write);

/* Match the modeled main/VP MMIO span in MemoryLayoutInit. */
#define APU_TRAP_BASE 0xFE800000u
#define APU_TRAP_END  0xFE830000u

static LONG CALLBACK veh_handler(PEXCEPTION_POINTERS ep)
{
    if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_ACCESS_VIOLATION) {
        uintptr_t fault_addr = ep->ExceptionRecord->ExceptionInformation[1];

        if (fault_addr >= 0xFD000000 && fault_addr < 0xFE000000) {
            return EXCEPTION_CONTINUE_SEARCH;
        }

        {
            uint32_t xbox_va =
                (uint32_t)(fault_addr - (uintptr_t)g_xbox_mem_offset);

            if (xbox_OhciOwnsAddress(xbox_va)
                    && xbox_OhciHandleMmio(ep->ContextRecord, xbox_va)) {
                return EXCEPTION_CONTINUE_EXECUTION;
            }

            if (xbox_va >= APU_TRAP_BASE && xbox_va < APU_TRAP_END
                    && apu_hook_handle_mmio(
                           ep->ContextRecord, fault_addr, xbox_va,
                           ep->ExceptionRecord->ExceptionInformation[0]
                               ? 1 : 0)) {
                return EXCEPTION_CONTINUE_EXECUTION;
            }
        }

        fprintf(stderr, "[CRASH] Access violation at RIP=0x%llX, fault addr=0x%llX (%s)\n",
            (unsigned long long)ep->ContextRecord->Rip,
            (unsigned long long)fault_addr,
            ep->ExceptionRecord->ExceptionInformation[0] ? "write" : "read");
        fprintf(stderr, "  Xbox regs: eax=0x%08X ecx=0x%08X edx=0x%08X esp=0x%08X\n",
            g_eax, g_ecx, g_edx, g_esp);
        fprintf(stderr, "  Xbox regs: ebx=0x%08X esi=0x%08X edi=0x%08X\n",
            g_ebx, g_esi, g_edi);
        fprintf(stderr, "  Xbox VA of fault: 0x%08X\n",
            (uint32_t)(fault_addr - (uintptr_t)g_xbox_mem_offset));
        fprintf(stderr, "  guest FS base: 0x%08X", g_fs_base);
        if (g_fs_base >= 0x1000 && g_fs_base < 0x04000000)
            fprintf(stderr, " fs:[4]=0x%08X",
                    *(const uint32_t *)((uintptr_t)g_xbox_mem_offset + g_fs_base + 4));
        fprintf(stderr, "\n");
        print_guest_context((void *)ep->ContextRecord->Rip);

        {
            uintptr_t *sp = (uintptr_t *)ep->ContextRecord->Rsp;
            fprintf(stderr, "  Native stack (first 8 return addrs):\n");
            for (int i = 0; i < 64 && sp[i]; i++) {
                if (sp[i] >= 0x140000000ULL && sp[i] < 0x150000000ULL) {
                    fprintf(stderr, "    [%d] 0x%llX\n", i, (unsigned long long)sp[i]);
                }
            }
        }
        fflush(stderr);
    }

    return EXCEPTION_CONTINUE_SEARCH;
}

/* ── WinMain ───────────────────────────────────────────────── */

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance,
                   LPSTR lpCmdLine, int nCmdShow)
{
    void *xbe_data = NULL;
    size_t xbe_size = 0;

    (void)hInstance;
    (void)hPrevInstance;
    (void)lpCmdLine;
    (void)nCmdShow;

    /* Proton/Wine gives a console-subsystem exe its own console, so stdio does
     * not reach the launching terminal. Send both streams to a file instead --
     * this also captures the runtime's [KERNEL]/[ICALL]/crash diagnostics. */
    {
        const char *log = getenv("RECOMP_LOG");
        if (!log || !*log) log = "recomp_boot.log";
        freopen(log, "w", stdout);
        freopen(log, "a", stderr);
        setvbuf(stdout, NULL, _IONBF, 0);
        setvbuf(stderr, NULL, _IONBF, 0);
    }

    /* Runtime configuration. These are the settings the known-working
     * scghost-recomp port uses to get past hardware init and present frames:
     * push-buffer execution, native NV2A fences + vblank, the emulated APU
     * with DSP passthrough, and the USB/OHCI + XInput stack the pad comes in
     * through. Set before any runtime init so every consumer sees them. */
    _putenv_s("RECOMP_WINDOW_TITLE", YOUR_GAME_TITLE);
    if (!getenv("RECOMP_AC97_READY"))
        _putenv_s("RECOMP_AC97_READY", "1");
    if (!getenv("RECOMP_DSP_ACK") && !getenv("RECOMP_APU_DSP_ACK"))
        _putenv_s("RECOMP_APU_DSP_ACK", "gp:0x810");
    if (!getenv("RECOMP_USB"))
        _putenv_s("RECOMP_USB", "1");
    if (!getenv("RECOMP_USB_NDP"))
        _putenv_s("RECOMP_USB_NDP", "2");
    {
        static const struct { const char *name, *value; } input_defaults[] = {
            {"RECOMP_XINPUT_SLOT", "auto"},
            {"RECOMP_KEYBOARD", "0"},
            {"RECOMP_INPUT_THRESHOLD", "30"},
            {"RECOMP_INPUT_DEADZONE_LEFT", "0"},
            {"RECOMP_INPUT_DEADZONE_RIGHT", "0"},
            {"RECOMP_INPUT_AXES", "0"}
        };
        for (size_t i = 0; i < sizeof(input_defaults) / sizeof(input_defaults[0]); i++) {
            if (!getenv(input_defaults[i].name))
                _putenv_s(input_defaults[i].name, input_defaults[i].value);
        }
    }
    if (!getenv("RECOMP_PB_EXEC"))
        _putenv_s("RECOMP_PB_EXEC", "1");
    if (!getenv("RECOMP_NV2A_NATIVE_FENCES"))
        _putenv_s("RECOMP_NV2A_NATIVE_FENCES", "1");

    printf("=== %s - Static Recompilation ===\n", YOUR_GAME_TITLE);
    printf("Loading XBE...\n");

    SymSetOptions(SYMOPT_DEFERRED_LOADS | SYMOPT_UNDNAME);
    SymInitialize(GetCurrentProcess(), NULL, TRUE);
    AddVectoredExceptionHandler(1, veh_handler);

    /* Step 1: Load XBE */
    if (!load_xbe(YOUR_GAME_XBE_PATH, &xbe_data, &xbe_size)) {
        printf("xbe path: %s\n", YOUR_GAME_XBE_PATH);
        printf("game dir: %s\n", YOUR_GAME_DIR);
        MessageBoxA(NULL, "Failed to load Ghost.xbe.\n"
                    "Place the game files in the 'game' subdirectory.",
                    "Recomp", MB_ICONERROR);
        return 1;
    }
    printf("XBE loaded: %zu bytes\n", xbe_size);

    /* Step 2: Initialize Xbox memory layout */
    printf("Initializing Xbox memory layout...\n");
    if (!xbox_MemoryLayoutInit(xbe_data, xbe_size)) {
        MessageBoxA(NULL, "Failed to initialize Xbox memory layout.",
                    "Recomp", MB_ICONERROR);
        free(xbe_data);
        return 1;
    }

    g_xbox_mem_offset = xbox_GetMemoryOffset();
    printf("Xbox memory mapped. Offset: 0x%llX\n", (unsigned long long)g_xbox_mem_offset);

    if (xbox_Nv2aNativeFencesEnabled() && !getenv("RECOMP_VBLANK"))
        _putenv_s("RECOMP_VBLANK", "1");

    /* Bring up the emulated APU (mapped variant: it resolves both contiguous
     * allocations and ordinary-RAM payloads through the DMA mapper). */
    if (getenv("RECOMP_AC97_READY")) {
        g_apu_state = mcpx_apu_init_standalone_mapped(
            (uint8_t *)((uintptr_t)g_xbox_mem_offset + XBOX_CONTIG_BASE),
            xbox_DmaPhysicalPointer);
        fprintf(stderr, "[BOOT] emulated APU %s\n",
                g_apu_state ? "up" : "FAILED to initialise");
    }

    /* Step 3: Initialize Xbox kernel */
    printf("Initializing Xbox kernel replacement...\n");
    xbox_kernel_init();

    /* Step 4: Set game directory for file I/O path translation */
    {
        extern void xbox_path_init(const char *game_dir, const char *save_dir);
        xbox_path_init(YOUR_GAME_DIR, NULL);
    }

    /* Step 5: Kernel bridge + input + USB/OHCI */
    printf("Initializing kernel bridge...\n");
    xbox_kernel_bridge_init();
    xbox_InputInit();
    xbox_OhciInit();

    /* Step 6: NV2A software-method dispatcher. The title's D3D miniport calls
     * the software method routine with a context pointer; registering both is
     * what lets present/fence/vblank actually happen. */
    if (xbox_Nv2aNativeFencesEnabled()) {
        if (xbox_Nv2aSoftwareMethodHandler(0x002C99B0u, 0x002D3D78u) < 0)
            return EXIT_FAILURE;
    } else {
        xbox_Nv2aMirrorFence(0x002D2148u, 0x2Cu, 0x30u);
        xbox_Nv2aFrameCounter(0x002D2148u, 0x1DE8u);
    }

    /* Step 7: Initialize stack */
    g_esp = XBOX_STACK_TOP;

    printf("\n=== Initialization complete ===\n");
    printf("Entry point: 0x%08X\n", YOUR_GAME_ENTRY_POINT);
    printf("ESP: 0x%08X\n", g_esp);

    if (!recomp_dispatch_init())
        fprintf(stderr, "[BOOT] flat dispatch unavailable; "
                        "indirect calls will use the binary search\n");

    xbox_WatchdogStart();

    /* Step 8: Call the recompiled entry point */
    printf("\nStarting game...\n");
    fflush(stdout);

    mainCRTStartup_001B3FBB();

    printf("\nGame returned. Cleaning up...\n");

    xbox_kernel_shutdown();
    xbox_MemoryLayoutShutdown();
    free(xbe_data);

    return 0;
}

/* ── XBE Loading ───────────────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size)
{
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "Cannot open XBE: %s\n", path);
        return FALSE;
    }

    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);

    if (size <= 0) {
        fclose(f);
        return FALSE;
    }

    void *data = malloc((size_t)size);
    if (!data) {
        fclose(f);
        return FALSE;
    }

    if (fread(data, 1, (size_t)size, f) != (size_t)size) {
        free(data);
        fclose(f);
        return FALSE;
    }

    fclose(f);
    *out_data = data;
    *out_size = (size_t)size;
    return TRUE;
}

/* Console entry point (for debugging -- lets you see printf output) */
int main(int argc, char **argv)
{
    /* --kbm: keyboard + mouse control. Parsed here because the console
     * subsystem gives us argv; WinMain only sees lpCmdLine. Set the seam
     * before WinMain, whose input defaults would otherwise force the keyboard
     * probe off (it is not the same thing). */
    for (int i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "--kbm")) {
            _putenv_s("RECOMP_KBM", "1");
            _putenv_s("RECOMP_KEYBOARD", "0");
        }
    }
    return WinMain(GetModuleHandle(NULL), NULL, GetCommandLineA(), SW_SHOW);
}
