#!/usr/bin/env python3
"""
Group the recompiler's 250-function chunks into one C file per original source
file.

The lifter splits by function count, which is the right thing for the compiler
and the wrong thing for a human: `recomp_0000.c` is 250 unrelated functions.
The source map knows which `.cpp` each function came from, so we can reassemble
the original translation units:

    src/game/recomp/gen/by_source/
      c__star__code__game__ui__vui.cpp.c   (the vui.cpp functions)
      c__star__code__game__ai__aiclass.cpp.c
      _unknown.c                            (unnamed / XDK library code)

Same C, same symbols, same dispatch; only the file boundaries change, so this is
a pure build-artifact transform. Compile EITHER the chunk files OR this
directory, never both.

Usage:
  group_by_source.py --gen-dir <dir> --functions <functions.json> --out-dir <dir>
"""
import argparse
import json
import os
import re

BANNER_RE = re.compile(r"/\*\*\n \* ([^\n]*)\n \* Original: 0x([0-9A-Fa-f]+)[^\n]*\n")

HEADER = (
    "/**\n"
    " * Starcraft: Ghost (Release) - recompiled, grouped by original source file\n"
    " * Auto-generated by recomp/tools/group_by_source.py; never hand-edit.\n"
    " */\n\n"
    "#define RECOMP_GENERATED_CODE\n"
    "#include \"recomp_funcs.h\"\n"
    "#include <math.h>\n\n"
)


def sanitize(path):
    s = re.sub(r"[^0-9A-Za-z]+", "_", path).strip("_")
    return s or "_unknown"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--gen-dir", required=True)
    ap.add_argument("--functions", required=True)
    ap.add_argument("--out-dir", required=True)
    a = ap.parse_args()

    src_of = {int(f["start"], 16): f.get("source_file") for f in json.load(open(a.functions))}
    os.makedirs(a.out_dir, exist_ok=True)

    buckets = {}   # sanitized source -> list of blocks
    chunks = sorted(p for p in os.listdir(a.gen_dir) if re.fullmatch(r"recomp_\d+\.c", p))
    for name in chunks:
        text = open(os.path.join(a.gen_dir, name)).read()
        heads = list(BANNER_RE.finditer(text))
        for i, m in enumerate(heads):
            start = m.start()
            end = heads[i + 1].start() if i + 1 < len(heads) else len(text)
            block = text[start:end].rstrip() + "\n\n"
            va = int(m.group(2), 16)
            buckets.setdefault(sanitize(src_of.get(va) or ""), []).append(block)

    total = 0
    for key, blocks in sorted(buckets.items()):
        total += len(blocks)
        with open(os.path.join(a.out_dir, key + ".c"), "w") as fh:
            fh.write(HEADER)
            fh.writelines(blocks)
    print(f"chunks: {len(chunks)}  functions: {total}  source files: {len(buckets)}")
    print(f"wrote {a.out_dir}")


if __name__ == "__main__":
    main()
